repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Admin linter/formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        name: admin linter
        args: [ --fix, --config=admin/pyproject.toml, admin ]
        files: "admin/"
      - id: ruff-format
        name: admin formatter
        args: [ --config=admin/pyproject.toml, admin ]
        files: "admin/"

  # Flags linter/formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        name: flags linter
        args: [ --fix, --config=flags/pyproject.toml, flags ]
        files: "flags/"
      - id: ruff-format
        name: flags formatter
        args: [ --config=flags/pyproject.toml, flags ]
        files: "flags/"

  # Python SDK linter/formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
        name: python sdk linter
        args: [ --fix, --config=sdk/python/pyproject.toml, sdk/python ]
        files: "sdk/python/"
      - id: ruff-format
        name: python sdk formatter
        args: [ --config=sdk/python/pyproject.toml, sdk/python ]
        files: "sdk/python/"

  # Admin type-check
  - repo: local
    hooks:
      - id: admin-type-check
        name: admin type check
        entry: "make -C admin type-check"
        language: system
        types: [python]
        require_serial: true
        verbose: true
        files: "admin/"

  # Flags type-check
  - repo: local
    hooks:
      - id: flags-type-check
        name: flags type check
        entry: "make -C flags type-check"
        language: system
        types: [python]
        require_serial: true
        verbose: true
        files: "flags/"

  # Python SDK type-check
  - repo: local
    hooks:
      - id: python-sdk-type-check
        name: python sdk type check
        entry: "make -C sdk/python type-check"
        language: system
        types: [python]
        require_serial: true
        verbose: true
        files: "python/sdk/"

  # Frontend linter
  - repo: local
    hooks:
      - id: frontend-lint
        name: frontend lint
        entry: "npm --prefix frontend run lint"
        language: system
        types_or: [javascript, jsx, ts, tsx]
        require_serial: true
        verbose: true
        files: "frontend/"
        pass_filenames: false
