site_name: Flagship
site_url: https://alexschimpf.github.io/flagship
site_author: Alex Schimpf

theme:
  name: rtd-dropdown

nav:
  - Overview: index.md
  - Installation: installation.md
  - Projects: projects.md
  - Context Fields: context-fields.md
  - Feature Flags: feature-flags.md
  - Users: users.md
  - SDK: sdk.md
  - UI: ui.md
  - Admin API: admin-api.md
  - Flags API: flags-api.md
  - Example: example.md
  - Development: development.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

plugins:
  - search

extra_css:
  - css/extra.css
