version: '3'
services:
    mysql:
        image: "mysql:8.2.0"
        container_name: mysql
        restart: on-failure
        ports:
            - 3306:3306
        volumes:
            - ./mysql/sql:/opt/sql
            - ./mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
            - mysql-volume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=test
    redis:
        image: "grokzen/redis-cluster:7.0.10"
        container_name: redis
        restart: on-failure
        ports:
            - 7000-7005:7000-7005
        volumes:
            - redis-volume:/redis-data
        environment:
            - IP=0.0.0.0
volumes:
    mysql-volume:
    redis-volume:
