version: '3'
services:
    mysql:
        image: "mysql:8.2.0"
        container_name: mysql
        restart: on-failure
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/sql:/opt/sql
            - ./mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
            - mysql-volume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=test
volumes:
    mysql-volume:
