services:
    mysql:
        image: "mysql:8.2.0"
        container_name: mysql
        restart: on-failure
        ports:
            - 3306:3306
        volumes:
            - ./mysql/sql:/opt/sql
            - ./mysql/init.sh:/docker-entrypoint-initdb.d/init.sh
            - mysql-volume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=test
            - DEV=1
        healthcheck:
            test: ["CMD", "mysqladmin", "-uroot", "-ptest", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 5s

    redis:
        image: "grokzen/redis-cluster:7.0.10"
        container_name: redis
        restart: on-failure
        ports:
            - 7000-7005:7000-7005
        volumes:
            - redis-volume:/redis-data
        environment:
            - IP=0.0.0.0
        healthcheck:
            test: ["CMD", "redis-cli", "-p", "7000", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 5s

volumes:
    mysql-volume:
    redis-volume:
