name: admin - pull request

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'admin/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: make -C admin install-dev
      - run: make -C admin lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: make -C admin install-dev
      - run: make -C admin type-check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: make -C admin install-dev
      - run: make -C admin unit-tests

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: make -C admin install-dev
      - run: docker-compose -f docker/docker-compose-deps.yml up --detach
      - run: make -C admin api-tests
