name: admin - deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: sergeysova/jq-action@v2
          id: version
          with:
            cmd: "jq .version admin/version.json -r"
        - run: |
            docker login -u alexschimpf -p ${{ secrets.DOCKER_TOKEN }} && \
            docker build . -t alexschimpf/flagship-admin:latest -t alexschimpf/flagship-admin:${{ steps.version.outputs.value }} && \
            docker push alexschimpf/flagship-admin:${{ steps.version.outputs.value }} && \
            docker push alexschimpf/flagship-admin:latest
          working-directory: ./admin

  release:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: sergeysova/jq-action@v2
          id: version
          with:
            cmd: "jq .version admin/version.json -r"
        - uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: admin/${{ steps.version.outputs.value }}
            release_name: Release admin/${{ steps.version.outputs.value }}
            draft: false
            prerelease: false
