name: flags - pull request

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'flags/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: make -C flags install-dev
      - run: make -C flags lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: make -C flags install-dev
      - run: make -C flags type-check

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: make -C flags install-dev
      - run: make -C flags unit-tests

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: make -C flags install-dev
      - run: docker-compose -f docker/docker-compose-deps.yml up --detach
      - run: make -C flags api-tests
