name: frontend - deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version frontend/package.json -r"
      - run: |
          docker login -u alexschimpf -p ${{ secrets.DOCKER_TOKEN }} && \
          docker build . -t alexschimpf/flagship-frontend:latest -t alexschimpf/flagship-frontend:${{ steps.version.outputs.value }} && \
          docker push alexschimpf/flagship-frontend:${{ steps.version.outputs.value }} && \
          docker push alexschimpf/flagship-frontend:latest
        working-directory: ./frontend

  release:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version frontend/package.json -r"
      - run: |
          git fetch origin main
          echo "COMMIT_SHA=$(git rev-parse origin/main)" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.CLI_PAT }}
      - run: git tag -a frontend/v${{ steps.version.outputs.value }} -m "Flagship Frontend v${{ steps.version.outputs.value }}" $COMMIT_SHA
        env:
          GITHUB_TOKEN: ${{ secrets.CLI_PAT }}
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CLI_PAT }}
        with:
          tag_name: frontend/v${{ steps.version.outputs.value }}
          release_name: "[Frontend] Release v${{ steps.version.outputs.value }}"
