name: frontend - pull request

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm --prefix frontend run lint
