name: frontend - deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
