name: sdk python - pull request

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'sdk/python/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: make -C sdk/python install-dev
      - run: make -C sdk/python lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: make -C sdk/python install-dev
      - run: make -C sdk/python type-check
