name: sdk javascript - deploy

on:
  workflow_dispatch:

jobs:
  # deploy:
  #   defaults:
  #     run:
  #       working-directory: ./sdk/javascript
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '20.x'
  #         registry-url: 'https://registry.npmjs.org'
  #     - run: npm install .
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    # needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .version sdk/javascript/package.json -r"
      - run: |
          git fetch origin main
          echo "COMMIT_SHA=$(git rev-parse origin/main)" >> $GITHUB_ENV
          git config --global user.email "aschimpf1@gmail.com"
          git config --global user.name "Alex Schimpf"
        env:
          GITHUB_TOKEN: ${{ secrets.CLI_PAT }}
      - run: |
          git tag -a sdk-javascript/v${{ steps.version.outputs.value }} -m "Flagship Javascript SDK v${{ steps.version.outputs.value }}" $COMMIT_SHA
          git push origin sdk-javascript/v${{ steps.version.outputs.value }}
        env:
          GITHUB_TOKEN: ${{ secrets.CLI_PAT }}
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.CLI_PAT }}
        with:
          tag_name: sdk-javascript/v${{ steps.version.outputs.value }}
          release_name: "[SDK - Javascript] Release v${{ steps.version.outputs.value }}"
